### PR TITLE
Detection of files with missing spec file

### PR DESCRIPTION
**Pull request by NiclasHedam**
This tries to address #49 as simple as possible. I think this solution seems rather horrifying, so I would like some advice on how to refactor it.

### CODE REVIEW

**Comment by NiclasHedam** [comment]
All good now!

**Comment by kasperisager** [comment]
Looking at the output, this really causes way too many false positives to be useful currently, so I've reverted the commit ☹️

**Comment by NiclasHedam** [comment]
What do you recommend doing then?

**Comment by kasperisager** [comment]
Given that automatically determining testable code does not really seem like an option, my previous recommendation still stands; add empty spec files for the files that _do_ need tests.

**Comment by kasperisager** [comment]
We have hundreds of files that can't and shouldn't be tested (e.g. files containing nothing but data), so a whitelist approach also seems suck 😢

**Comment by NiclasHedam** [comment]
Absolutely, but the status quo is not acceptable either. We cannot just ignore untested files as if there are no issues with them.

**Comment by kasperisager** [comment]
Unless we can reliably call them out, there's little else we can do but ignore them though. I'm happy to consider a revised approach, but reliability is a requirement.

**Pull request merged**
