### PR TITLE
Rename `tree.Node#serializationId` to `tree.Node#internalId`.

### PR DESCRIPTION
**Pull request by Jym77**
This makes it a bit more general.

### CODE REVIEW

**Comment by Jym77** [comment]
!pr extract

**Comment by Jym77** [comment]
@jfer-siteimprove @mvy-siteimprove FYI. I believe this will break the Code Checker Page Report that only receives the JSON serialization and thus need to read the correct field name.

**Comment by mvy-siteimprove** [comment]
> @jfer-siteimprove @mvy-siteimprove FYI. I believe this will break the Code Checker Page Report that only receives the JSON serialization and thus need to read the correct field name.

Thanks for the heads up @Jym77. Good that the `serializationId` is still available as an alias. We can safely deploy this, update our usage and then delete the alias.

**Comment by Jym77** [comment]
> > @jfer-siteimprove @mvy-siteimprove FYI. I believe this will break the Code Checker Page Report that only receives the JSON serialization and thus need to read the correct field name.
> 
> Thanks for the heads up @Jym77. Good that the `serializationId` is still available as an alias. We can safely deploy this, update our usage and then delete the alias.

🤔 I am not sure because you only read the JSON, not the actual object.
Or should I keep the `serializationId` alias in the JSON too?

**Comment by Jym77** [comment]
> > > @jfer-siteimprove @mvy-siteimprove FYI. I believe this will break the Code Checker Page Report that only receives the JSON serialization and thus need to read the correct field name.
> > 
> > 
> > Thanks for the heads up @Jym77. Good that the `serializationId` is still available as an alias. We can safely deploy this, update our usage and then delete the alias.
> 
> 🤔 I am not sure because you only read the JSON, not the actual object. Or should I keep the `serializationId` alias in the JSON too?

Should be good now ☺️

**Review by rcj-siteimprove — APPROVED** [review]

**Pull request merged**
