### PR TITLE
Introduce calculatable numeric types

### PR DESCRIPTION
**Pull request by Jym77**
Part of #1202 

* Duplicate all `Numeric` sub-types into calculatable versions.
* Use calculatable numeric in style properties.
* Keep fixed numeric in more complex types (color, shadow, …)
* Assorted clean up.
* Automatically infer dimension's type kind (`Unit,Length`, …) and canonical unit (`px`, …) from the type representation (`"length"`, …)
* Introduce a `Foo.Canonical` abstraction; ultimately all CSS types should have it and the other intermediate abstractions (`Calculated`, `Fixed`) should probably be hidden away.

### CODE REVIEW

**Comment by Jym77** [comment]
!pr extract

**Comment by Jym77** [comment]
!pr extract

**Comment by Jym77** [comment]
!pr extract

**Comment by Jym77** [comment]
!pr extract

**Review by rcj-siteimprove — APPROVED** [review]
Looks good, just found one typo in a changeset

**Review by rcj-siteimprove — APPROVED** [review]

**Pull request merged**
